# This workflow will upload the CSV_VIZ Python package using Twine when a release is created

name: Upload CSV_VIZ Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Set up the Python environment
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # You can specify a particular version if needed

    # Install necessary dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    # Build the Python package
    - name: Build package
      run: python -m build

    # Optionally run tests before publishing
    # - name: Run tests
    #   run: |
    #     python -m pip install -r requirements.txt
    #     pytest

    # Publish the package to PyPI
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
